before_commands:
    - "composer update --prefer-source"

tools:
#    php_code_coverage:
#        enabled: true
#        test_command: ./vendor/bin/phpunit -c phpunit.xml.dist
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["module/*", "upgrade/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["bin", "data", "config", "vendor"]
    php_cs_fixer:
        enabled: true
    php_loc:
        enabled: true
        excluded_dirs: ["bin", "data", "config", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["module/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["bin", "data", "config", "vendor"]
# php_analyzer is disabled because `composer install` doesn't work (missing mongo and postgres)
# can be fixed by committing composer.lock to the repository
#    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["module/*"]
    sensiolabs_security_checker: true
