tools:
    # php_code_coverage:
    #     enabled: true
    #     test_command: ./vendor/bin/phpunit -c phpunit.xml.dist
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["module/*"]
        config:
            sniffs:
                psr2:
                    namespaces:
                        use_declaration_sniff: false
    # php_cpd:
    #     enabled: true
    #     excluded_dirs: ["bin", "data", "config", "vendor"]
    php_cs_fixer:
        enabled: true
    php_loc:
        enabled: true
        excluded_dirs: ["bin", "data", "config", "vendor"]
    # php_mess_detector:
    #     enabled: true
    #     filter:
    #         paths: ["module/*"]
    # php_pdepend:
    #     enabled: true
    #     excluded_dirs: ["bin", "data", "config", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["module/*"]
        config:
            use_statement_fixes:
                preserve_multiple:    true
    # sensiolabs_security_checker: true
