<?php

namespace StoreBundle\Repository;

use CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * Store
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Store extends EntityRepository
{
    public function findAllQuery()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('s')
            ->from('StoreBundle\Entity\Store', 's')
            ->getQuery();

        return $resultSet;
    }
}
